### ISSUE TITLE
Colab Link for notebook 3.4 Softmax Regression isnt working.

### ISSUE THREAD

**Issue by RaghavPrabhakar66** [developer-student-club-thapar/d2l-study-group#9]
@animesh-007 Link is in correct format, still colab is showing error.

**Comment by animesh-007** [comment]
@Raghav1503 Yes, I just checked. Actually, this section only contains theory and no code that's why there is a zero-sized notebook.
I think it's better to remove this to avoid confusion. What's say?

**Comment by RaghavPrabhakar66** [comment]
@animesh-007 If thats the case we can just remove the colab link from Readme.md and close the issue.

**Comment by animesh-007** [comment]
Fixed in #14
